
# @auther :generated by pyautomation
from tests.pages.search_page import SearchPage
from pyautomation.web.webtest import WebTest
from pyautomation.web.create_page import CreatePage
     
class TestSearch(WebTest):
    def test_search(self):
        page = CreatePage.get(SearchPage, self.driver)
        print(page.search_field.text)
        page.search("test")
        assert self.driver.title.startswith("test"), "title does not match"
        